/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/router.glb --output src/components/Router.jsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function RouterGLB(props) {
  const { nodes, materials } = useGLTF('/models/router.glb')

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Circle001.geometry}
        material={materials['Material.004']}
        position={[2.281, 0.084, 0.161]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.067, 0.014, 0.079]}
      />

      <mesh
        geometry={nodes.Circle002.geometry}
        material={materials['Material.004']}
        position={[2.282, 0.129, 0.175]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.013, 0.046, 0.043]}
      />

      <mesh
        geometry={nodes.Circle003.geometry}
        material={materials['Material.004']}
        position={[2.282, 0.102, -0.175]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.055, 0.014, 0.045]}
      />

      <mesh
        geometry={nodes.Circle004.geometry}
        material={materials['Material.004']}
        position={[2.284, 0.077, 0.407]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.107, 0.043, 0.107]}
      />

      <mesh
        geometry={nodes.Circle005.geometry}
        material={materials['Material.004']}
        position={[2.281, 0.119, -0.173]}
        rotation={[-1.379, 0, -Math.PI / 2]}
        scale={[0.055, 0.011, 0.024]}
      />

      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Material}
      />

      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials.Material}
        scale={[2.233, 0.3, 3.559]}
      />

      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials['Material.002']}
        position={[-5.986, -0.027, 1.875]}
        scale={[0.234, 0.126, 0.234]}
      />

      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials['Material.001']}
        position={[-5.986, -0.027, 1.873]}
        scale={[0.234, 0.129, 0.234]}
      />

      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials['Material.002']}
        position={[-5.986, -0.027, 1.873]}
        scale={[0.234, 0.129, 0.234]}
      />

      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials['Material.002']}
      />

      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials['Material.002']}
      />

      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials['Material.002']}
      />

      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials['Material.001']}
      />

      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials.Material}
      />

      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials['Material.003']}
        position={[2.088, 0.357, 0.171]}
        scale={[0.005, 0.038, 0.029]}
      />

      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials['Material.003']}
        position={[2.088, 0.357, 0.057]}
        scale={[0.005, 0.038, 0.029]}
      />

      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials['Material.003']}
        position={[2.088, 0.357, -0.054]}
        scale={[0.005, 0.038, 0.029]}
      />

      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials['Material.003']}
        position={[2.088, 0.357, -0.161]}
        scale={[0.005, 0.038, 0.029]}
      />

      <mesh
        geometry={nodes.Circle.geometry}
        material={materials['Material.004']}
        position={[2.281, 0.102, 0.241]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.057, 0.012, 0.057]}
      />

      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials.Material}
      />
    </group>
  )
}

useGLTF.preload('/models/router.glb')